# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.18"
  amd64: "ghcr.io/home-assistant/amd64-base:3.18"
  armhf: "ghcr.io/home-assistant/armhf-base:3.18"
  armv7: "ghcr.io/home-assistant/armv7-base:3.18"
  i386: "ghcr.io/home-assistant/i386-base:3.18"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: MITM Proxy"
  org.opencontainers.image.description: "A free and open source interactive HTTPS proxy for intercepting and inspecting network traffic."
  org.opencontainers.image.source: "https://github.com/davet2001/home-assistant-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
