# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Podtube
version: "0.0.2"
slug: podtube
description: >-
  PodTube converts YouTube playlists and channels into podcast RSS feeds.
url: "https://github.com/davet2001/home-assistant-addons/tree/main/podtube"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
init: false
ports:
  80/tcp: 9876
options:
  google_api_key: null
schema:
  google_api_key: "str"
image: "ghcr.io/davet2001/{arch}-addon-podtube"
