version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      time: "06:00"
    # Raise pull requests for version updates
    # to github-actions against the `dev` branch
    target-branch: "dev"
